### ISSUE TITLE
Second Gallery after Slick-Gallery won't be shown

### ISSUE THREAD

**Issue by michakrapp** [tyrann0us/slick-slider#36]
Bug after the newest update. (I think happend not before)

If you have two galleries on one page and for the first you activated Slick but not on the second, then the second non-slick gallery will not be shown. 
Looks like the images don't load.

Tested it on a fresh install with standard-theme to make sure it's not my site.

**Example here:** 
Below the text is a second gallery which does not show up.
https://mcx.sunlab.eu/de/farben-beschichtungen/

**Comment by tyrann0us** [comment]
Hi @michakrapp,
thanks for pointing this out. I can confirm the bug.
It's caused because the `src`,  `srcset` and `sizes` attributes of the images are beeing swapped by their "lazy" counterparts, even for following galleries.
I will commit a fix to GitHub right now and later to the WordPress plugin repo.

**Comment by tyrann0us** [comment]
@michakrapp, please test this fix, it's working for me.

**Comment by tyrann0us** [comment]
Sorry, this was half-cooked: The fix disables the lazy loading feature completely instead of only applying to following galleries.
I will provide a correctly working fix later on.

**Comment by tyrann0us** [comment]
I edited the commit. If you cloned this repo, make sure to [hard fetch](https://stackoverflow.com/questions/1125968/how-do-i-force-git-pull-to-overwrite-local-files) the changes.
A new version will be released soon.

**Comment by michakrapp** [comment]
Thanks for the fast respond.
Update works.

No I only did a fork for the changes.
