### ISSUE TITLE
Not working on WordPress 5.0.x

### ISSUE THREAD

**Issue by b4dnewz** [tyrann0us/slick-slider#40]
The slick settings template is not showing.

WordPress v5.0.3

**To Reproduce**
wp core download  // it will download the last stable version
wp core install [with options]
wp plugin install slick-slider
Go to the Media page or open the Media Gallery
The plugin settings are not shown

**Additional context**
I see the actual template code is in the page, so it could be just a change in the __wp.media__ api.
![image](https://user-images.githubusercontent.com/29862596/51747626-5a1eae00-20aa-11e9-8bb2-ae9a90dc62e8.png)

I'm trying to debug it but I don't know very well WordPress and especially the javascript media api, if you have any suggestion it's appreciated.

**Comment by tyrann0us** [comment]
Hi @b4dnewz, I'm sorry to inform you that the plugin currently does _not_ work with the Block Editor that ships with WordPress 5.0+. It's tested up to WordPress 4.8.* (https://github.com/tyrann0us/slick-slider/blob/master/readme.txt#L6) but should work with WordPress 4.9.* too.

As I said in https://wordpress.org/support/topic/compatibility-wp-5-0/#post-11006377 I currently have absolutely no ETA when it will become compatible.

**Comment by b4dnewz** [comment]
I'm willing to help.
do you have any hint of what may be the cause?

This sources https://codex.wordpress.org/Javascript_Reference/wp are not well documented unfortunately, also the change notes i'm looking at https://wordpress.org/support/wordpress-version/version-5-0/#for-developers doesn't say to much

**Comment by tyrann0us** [comment]
>do you have any hint of what may be the cause?

The entire plugin not supporting the Block Editor. 😁 No, seriously, I really appreciate your will to help!

But honestly, I just recently started working with the editor. That said, I wasn't able to check how the new Gallery block works.
Maybe https://wordpress.stackexchange.com/a/298441/48203 is a good start. If you contribute code in a PR, please make sure to use ES.Next.
Thanks!

**Comment by b4dnewz** [comment]
awesome, I also found this https://code.tutsplus.com/series/wordpress-gutenberg-block-api--cms-1281 
I hope I'll make it soon ;)

**Comment by b4dnewz** [comment]
ok, actually I give up, it took me a too much time without success, the blocks and core-blocks, documentation is still pretty unclear also wordpress isn't my favourite thing so i'm not so encouraged to continue. :smile: 

By the way, looking at your plugin code, good job, very clear and well structured.
